### PR TITLE
Fix #31: Windows: default compiler does not persist.

### LINKED ISSUE #31: Windows: default compiler does not persist
Using 0.4.3 in Windows 7, calling ```dvm install 2.066.1``` fetches and installs correctly. Then ```dvm -d use 2.066.1``` adds the compiler directory to my path variable, and it works fine. If I exit the shell, and open a new one, the path settings are gone, and no dmd is found. 

When I installed dvm I did it in a terminal which had admin rights, and I have tried setting the default compiler also with an elevated terminal, but no luck. 

Have I missed something?

### PR DESCRIPTION
**Pull request by Abscissa**
This seems to work for me on Win7.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Hmm, I'm pretty sure I made this change myself and it didn't work (Windows 8). But I'll try this again and see what happens.

**Comment by Abscissa** [comment]
On 09/11/2015 09:03 AM, jacob-carlborg wrote:
> Hmm, I'm pretty sure I made this change myself and it didn't work (Windows 8). But I'll try this again and see what happens.
>

I'd had the same thought too, actually. I wonder if maybe we both forgot 
to ```bin\dvm install dvm``` the newly-built exec before testing it. 
(Since normally, running ```dvm ...``` is supposed to run a shell script 
which then invokes the real executable and then sources any shell 
commands returned by the executable.)

I forgot that this time and ```bin\dvm use -d``` didn't work at all 
(neither did plain ```bin\dvm use```). But then after I did ```bin\dvm 
install dvm``` and then ```dvm use ...``` and it worked fine both with 
and without ```-d```.

**Comment by jacob-carlborg** [comment]
Ah, that might be the case.

**Comment by jacob-carlborg** [comment]
It does work. It's just my crappy terminal emulator that doesn't work :disappointed:.

**Pull request merged**
